name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        v1_2=$(cat VERSION)
        v3=$(( ($(date +%y%m%d)) ))
        v4=$(( ($(date +%H) * 3600) + ($(date +%M) * 60) + ($(date +%S) * 1) ))
        echo Auto versioning calculation: $v1_2.$v3.$v4
        echo Autoversioning done.
